# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Download Example API from steam workshop
        run: |
          wget -q https://steamusercontent-a.akamaihd.net/ugc/358399162719791713/17B6973C6F60561466E081AEE0EF35ABC2FB19F2/ -O mod_publish_data_file.zip
          
      - name: Unzip Example API
        run:  unzip -qq ./mod_publish_data_file.zip -d ./exampleapi || echo "Suppressing unzip errors"
     
      - name: Make the mod using the given makefile
        run: |
          sudo chmod +x exampleapi/KWAD\ builder/bin/linux/builder
          echo KWAD_BUILDER="./exampleapi/KWAD\ builder/bin/linux/builder" > makeconfig.mk
          echo INSTALL_PATH="./install" > makeconfig.mk
          make install
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "MoreMissions"
          path: install
